### ISSUE TITLE
notifier message does not always include the URL to the commit

### ISSUE THREAD

**Issue by gregwhorley** [jhegg/github-desktop-notifier#10]
An example of this is a recent commit by @jhegg where a feature branch was created in a repo and code was committed. The GDN shows the master_branch, pusher_type, ref, and ref_type inside the "payload" block, but no commit URL or commit message. It should be noted that this particular notification is of type "CreateEvent" while the other notifications that include commit URL are of type "PushEvent". Also I am seeing "GollumEvent" notifications that, I think, have to do with wiki page updates.

While the "CreateEvent" notification is gathered by GDN, there is no notification of the subsequent commit that I got an e-mail notification for, which I assume would be the "PushEvent".

**Comment by jhegg** [comment]
Yeah, I need to parse those out and give a better description for them. `CreateEvent` is for things like creating a branch, a repo, an issue, etc. But, keep in mind the app is currently displaying all of the available information, it's the raw JSON that was retrieved from GitHub; if it's not in that output, it's not readily available. But it could be something that can be constructed based on other data in the event.

**Comment by gregwhorley** [comment]
Would it be a big effort to add filtering capability by type?  The types being createevent pushevent etc

**Comment by jhegg** [comment]
Not really. Could you open a new issue/request for that, though? It's easier to track that way.

**Comment by jhegg** [comment]
@gwhorley The messages should now be more clear about what they are. Let me know what you think.
