### ISSUE TITLE
Preferences window: move text fields below title

### ISSUE THREAD

**Issue by gregwhorley** [jhegg/github-desktop-notifier#7]
UPDATE: I am unable to add a label to this issue for some reason. File this under 'enhancement request'.

When I opened the app for the first time, a new window appeared that directed me to Edit -> Preferences. When I opened the Preferences window, I was greeted with two text fields with titles: GitHub O... and GitHub u... . I had to stretch the window out to see the full titles. It would be better if the text fields were either shortened or moved directly below the title.

**Comment by jhegg** [comment]
I think on Windows this problem doesn't show up. I probably have some margin setting incorrect on the labels. But I do agree that moving the labels above the text input fields is probably a better solution, unless I make them less verbose.

I still have to put the GitHub Enterprise hostname setting/option in there. Probably needs some actual design. :art:

**Comment by jhegg** [comment]
@gwhorley Could you please take a look at the changed Preferences UI? It should look better on all platforms.
